# This is a basic workflow to help you get started with Actions

name: Test github actions

# Controls when the workflow will run
on:
  # Triggers the workflow on pull request events but only for the "main" branch
  pull_request:
    types:
      - labeled
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  create-jira-ticket:
    if: github.event.label.name == 'test request'
    runs-on: ubuntu-latest

    steps:
      - name: Create JIRA Ticket for Testing
        run: |
          echo hello tag!
          echo ${{ github.event.pull_request.number }}
